# Generated by Django 2.0.7 on 2018-07-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tag_id', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.IntegerField(default=0)),
                ('tag_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('birth_day', models.DateTimeField()),
                ('favorite', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UnitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.PetInfo'),
        ),
        migrations.AddField(
            model_name='petimage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.UnitInfo'),
        ),
        migrations.AddField(
            model_name='petfriend',
            name='friend_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='pets.PetInfo'),
        ),
        migrations.AddField(
            model_name='petfriend',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pets.PetInfo'),
        ),
    ]
