# Generated by Django 2.0.7 on 2018-07-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
