# Generated by Django 2.0.7 on 2018-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20180704_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
